In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/WDICSV.csv")
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.145833,18.685118,19.205632,19.742772,20.332679,20.862800,21.419621,21.996456,22.541440,NaN
1,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.259936,7.606712,7.926604,8.309896,8.704591,9.106640,9.480804,9.903209,10.288154,NaN
2,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.741988,39.052626,39.321068,39.649534,39.968299,40.354628,40.723805,41.026351,41.289974,NaN
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,33.922276,38.859598,40.223744,43.035073,44.390861,46.282371,48.127211,48.801258,50.667516,NaN
4,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,16.495064,24.584906,25.375037,26.941984,28.983183,30.909991,32.709837,33.747222,35.240236,NaN

In [ ]:
df.isnull().sum()

Country Name           0
Country Code           0
Indicator Name         0
Indicator Code         1
1960              109680
                   ...
2020               59533
2021               60714
2022               64594
2023               70907
2024               84418
Length: 69, dtype: int64

In [ ]:
key_indicators = [
    "NY.GDP.MKTP.KD.ZG",
    "FP.CPI.TOTL.ZG",
    "SL.UEM.TOTL.ZS"
]

df = df[df["Indicator Code"].isin(key_indicators)]

In [ ]:
df_long = df.melt(
    id_vars=["Country Name", "Country Code", "Indicator Name", "Indicator Code"],
    var_name="Year",
    value_name="Value"
)

In [ ]:
df_long = df_long[df_long["Year"].str.isnumeric()]
df_long["Year"] = df_long["Year"].astype(int)

In [ ]:
aggregate_codes = ["WLD", "HIC", "LIC", "MIC", "LMY", "UMC"]
df_long = df_long[~df_long["Country Code"].isin(aggregate_codes)]

In [ ]:
df_long = df_long.sort_values(
    ["Country Name", "Indicator Code", "Year"]
)

df_long["YoY_Change"] = df_long.groupby(
    ["Country Name", "Indicator Code"]
)["Value"].diff()

In [ ]:
df_long["Significant_Shift"] = df_long["YoY_Change"].abs() > 5

In [ ]:
df_long.to_csv("wdi_cleaned.csv", index=False)

In [ ]:
df_long

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Value,YoY_Change,Significant_Shift
148,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,1960,NaN,NaN,False
387,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,1961,NaN,NaN,False
626,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,1962,NaN,NaN,False
865,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,1963,NaN,NaN,False
1104,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,1964,NaN,NaN,False
...,...,...,...,...,...,...,...,...
14477,Sub-Saharan Africa (excluding high income),SSA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2020,6.966628,0.394826,False
14716,Sub-Saharan Africa (excluding high income),SSA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2021,7.185094,0.218466,False
14955,Sub-Saharan Africa (excluding high income),SSA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2022,6.393599,-0.791494,False
15194,Sub-Saharan Africa (excluding high income),SSA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2023,6.042158,-0.351442,False
15433,Sub-Saharan Africa (excluding high income),SSA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,2024,5.946418,-0.095740,False